version: 1.2
workflows:
  - name: read_in_reports
    subclass: WDL
    primaryDescriptorPath: /workflows/PhyloSKA_Test/read_in_reports.wdl  # absolute path
    readMePath: /workflows/PhyloSKA_Test/README.md # absolute path
    authors:
      - name: VK
        email: vkhadka@broadinstitute.org
  - name: strain_to_skf
    subclass: WDL
    primaryDescriptorPath: /workflows/PhyloSKA_Test/strain_to_skf.wdl  # absolute path
    readMePath: /workflows/PhyloSKA_Test/README.md # absolute path
    authors:
      - name: VK
        email: vkhadka@broadinstitute.org
  - name: ska_compare
    subclass: WDL
    primaryDescriptorPath: /workflows/PhyloSKA_Test/ska_compare.wdl  # absolute path
    readMePath: /workflows/PhyloSKA_Test/README.md # absolute path
    authors:
      - name: VK
        email: vkhadka@broadinstitute.org
  - name: ska_fasta
    subclass: WDL
    primaryDescriptorPath: /workflows/PhyloSKA_Test/ska_fasta.wdl  # absolute path
    readMePath: /workflows/PhyloSKA_Test/README.md # absolute path
    authors:
      - name: VK
        email: vkhadka@broadinstitute.org
  - name: mummer
    subclass: WDL
    primaryDescriptorPath: /workflows/PhyloSKA_Test/mummer_analysis.wdl  # absolute path
    readMePath: /workflows/PhyloSKA_Test/README.md # absolute path
    authors:
      - name: VK
        email: vkhadka@broadinstitute.org
  - name: 2025-tutorial
    subclass: WDL
    primaryDescriptorPath: /workflows/2025-wdl-tutorial/test_workflow.wdl  # absolute path
    readMePath: /workflows/2025-wdl-tutorial/README.md # absolute path
    authors:
      - name: VK
        email: vkhadka@broadinstitute.org
