version: 1.2
workflows:
  - subclass: <CWL | WDL | NFL | GALAXY>
    primaryDescriptorPath: /workflows/PhyloSKA_Test/read_in_reports.wdl  # absolute path
    readMePath: /workflows/PhyloSKA_Test/README.md # absolute path
    authors:
      - name: VK
        email: vkhadka@broadinstitute.org